name 'jasper-openbsd_facts'
version '0.1.0'
author 'jasper'
license 'ISC'
summary 'Collection of additional facts for OpenBSD'
description 'Various facts specific to OpenBSD'
project_page 'https://github.com/jasperla/openbsd_facts'
